# Generated by Django 3.1.3 on 2020-11-19 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_todolist_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='content',
        ),
    ]
