# Generated by Django 3.1.3 on 2020-11-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_auto_20201120_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='content_2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default='2020-11-22'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(default='2020-11-22'),
        ),
    ]
